version: '3'
services:

  source:
    build: "source/"
    volumes:
      - ./source/src/:/code

  entry:
    build: "entry/"
    ports:
      - "8080:5000"
    volumes:
      - ./entry/src/:/code

  reception:
    build: "reception/"
    expose:
      - "9092"
      - "2181"
    ports:
      - "9092"
      - "2181"

  pc:
    build: "./producers-consumers"
    volumes:
      - ./producers-consumers:/code

  traitement_job:
    image: "flink"
    expose:
      - "6123"
    ports:
      - "8082:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./traitement/:/code

  traitement_task:
    image: "flink"
    expose:
      - "6121"
      - "6122"
    depends_on:
      - traitement_job
    command: taskmanager
    links:
      - "traitement_job:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    volumes:
      - ./traitement/:/code

  historisation:
    build: "historisation/"
    environment:
      MONGO_INITDB_ROOT_USERNAME: jiaye
      MONGO_INITDB_ROOT_PASSWORD: kk
    volumes:
      - ./historisation/:/code

  presentation:
    build: "presentation/"
    environment:
      FLASK_APP: app.py
    ports:
      - "8081:5000"
    volumes:
      - ./presentation/src:/code

